### ISSUE TITLE
既然谈到了分形，那么store 嵌套应该怎么做？

### ISSUE THREAD

**Issue by lusess123** [forsigner/stamen#1]

**Comment by forsigner** [comment]
没太明白这里所说的嵌套

**Comment by lusess123** [comment]
> 没太明白这里所说的嵌套

就是  一个 store 引用 另一个store ， store 嵌套store , 或者两个同一个类型的store 互相引用

**Comment by forsigner** [comment]
如果把你这里的引用理解成**互相访问和更新**的话，因为每个 store 都有自己的 get 和 dispatch 方法，使用各自的 get 和 dispatch 可以完成**互相访问和更新**，比如：

```js
const userStore = UserStore.useStore();
const todoStore = TodoStore.useStore();

const name = userStore.get(s => s.name);
const todos = TodoStore.get(s => s.todos);

// 这是 name 的 dispatch: name.dispatch

const App = () => (
  <div>
    <span>{name}</span>
    <div>
      {todos.map(item => {
        <div>
          <span>{item.name}</span>
        </div>;
      })}
    </div>
  </div>
);
```

当然，这是在 Component 里的使用，也是最常用的场景，如果需要在 Component 外使用的话，暂时不支持，很少有这样的业务场景，不过技术上也不难实现。

**Comment by lusess123** [comment]
> 如果把你这里的引用理解成**互相访问和更新**的话，因为每个 store 都有自己的 get 和 dispatch 方法，使用各自的 get 和 dispatch 可以完成**互相访问和更新**，比如：
> 
> ```js
> const userStore = UserStore.useStore();
> const todoStore = TodoStore.useStore();
> 
> const name = userStore.get(s => s.name);
> const todos = TodoStore.get(s => s.todos);
> 
> // 这是 name 的 dispatch: name.dispatch
> 
> const App = () => (
>   <div>
>     <span>{name}</span>
>     <div>
>       {todos.map(item => {
>         <div>
>           <span>{item.name}</span>
>         </div>;
>       })}
>     </div>
>   </div>
> );
> ```
> 
> 当然，这是在 Component 里的使用，也是最常用的场景，如果需要在 Component 外使用的话，暂时不支持，很少有这样的业务场景，不过技术上也不难实现。

嗯， 我说的就是  Component 外的，甚至是 store 内部的，或者这两个store 是同一个类型的两个不同实例

**Comment by forsigner** [comment]
component 外读取 state 可以用 getState()， 更新用 dispatch
