### ISSUE TITLE
npm package 缺少类型文件声明

### ISSUE THREAD

**Issue by waltcow** [forsigner/stamen#19]
[Including declarations in your npm package](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

![image](https://user-images.githubusercontent.com/3941174/62764761-37416d80-bac1-11e9-8cc3-21251421ff62.png)

**package.json** 文件 缺少 **types** 的声明，导致编辑器无法跳转到对应的定义文件

**Comment by forsigner** [comment]
应该是会自动的 不需要package.json声明，你的什么编辑器

**Comment by waltcow** [comment]
Webstorm

forsigner <notifications@github.com> 于 2019年8月16日周五 上午9:45写道：

**Comment by forsigner** [comment]
编辑器会自动识别 types
