### ISSUE TITLE
建议把GraphQL部分拆分出来

### ISSUE THREAD

**Issue by mapoio** [forsigner/stamen#5]
非常赞的项目， 我已经打算在我的应用中使用这个作为我的状态管理了。但是有个问题，我看了一下代码，发现里面包含了GraphQL的API调用，仅我个人观点觉得，可能拆出来更好一些，毕竟不是每一个项目都会用到GraphQL作为接口入口。

**Comment by forsigner** [comment]
恩 这个我后续独立拆开来

**Comment by forsigner** [comment]
已去除 graphQL相关
